<?xml version="1.0"?>
<package format="3">
  <name>pointcloud_tools</name>
  <version>0.1.0</version>
  <description>Pointcloud processing tools for industrial LIO system.</description>
  <maintainer email="ops@example.com">ops</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
