<?xml version="1.0"?>
<package format="3">
  <name>system_bringup</name>
  <version>0.1.0</version>
  <description>System bringup launch package.</description>
  <maintainer email="ops@example.com">ops</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pointcloud_tools</exec_depend>
  <exec_depend>map_manager</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
